// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModQImagesCompositeKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModQImagesCompositeKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "202008261740120_Mod-QImages-CompositeKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
